### ISSUE TITLE
Allow for use of User Assigned Managed Identity

### ISSUE THREAD

**Issue by alexverboon** [briandelmsft/SentinelAutomationModules#424] opened 2023-07-12 11:49 UTC
**Is your feature request related to a problem? Please describe.**
At present the solution creates a managed identity for each playbook

**Describe the solution you'd like**
In order to reduce the number of managed identities, I would like to use a User Assigned Managed Identity. 

**Additional context**
Of course I could modify the playbooks myself to use a user assigned managed identity, but I wanted to avoid that this blocks future updates. Hence would it be possible to allow for specifiying the UAMI when installing the solution, so that the script takes care of assigning the permissions etc. ?

**Comment by briandelmsft** [comment] 2023-07-12 13:50
@alexverboon This will be supported in STAT v2, preview will be coming out soon

**Comment by briandelmsft** [comment] 2023-07-12 13:51
Duplicate of #58

**Comment by briandelmsft** [comment] 2023-07-17 02:44
@alexverboon 

STAT v2 Preview is ready for you to try.  This is a major move forward from previous versions of STAT, now using an Azure Functions backend and Logic Apps front end.  The look and feel is the same as v1, but the improvements on the backend are substantial. This is also a complete rewrite of all of the backend functionality, so do be aware there may be some undiscovered bugs, though there are no known issues in this build.  If you encounter any bugs, or even unexpected changes in functionality from previous version please open an issue no matter how small the issue may be.

This build includes the following new features:

- Backend of STAT is now using Azure Functions instead of Logic apps
- Support for User Assigned Managed Identities, Service Principal and Multi Tenant service principal authentication (in addition to existing system assigned managed id support)
- Support for the Sentinel Alert trigger (in addition to existing incident trigger)
- Ability to create a new Sentinel incident from an alert and automatically link the alert
- Additional performance and other minor improvements

The Preview [deployment](https://github.com/briandelmsft/SentinelAutomationModules/tree/statv2_preview/Deploy) can be found only in the statv2_preview branch of this repo as well as supporting [documentation](https://github.com/briandelmsft/SentinelAutomationModules/blob/statv2_preview/Docs/). That includes documentation specific to [multi-tenant/MSSP](https://github.com/briandelmsft/SentinelAutomationModules/blob/statv2_preview/Docs/mssp.md) scenarios.

The main branch does not contain any information about v2 at this time, so ensure you select the correct branch.

**Closed** 2024-04-18 17:38 UTC
Labels: enhancement, duplicate
